#!/bin/bash

if [ "$1" == "-a" ]; then
	for i in$(ls $2); do
		if [ $(echo $2/$i | grep -c "log") -eq 1 ]; then
			echo "moviendo $2/$i a /var/log"
			mv $2/$i /var/log
		fi
	done
	exit 0
fi

if  ["$1" == "-b" ]; then
	cont=0
	for i in $(ls $2); do
		if [ -x $2/$i ]; then
			cont=$((cont+1))
		fi
	done
	echo "cantidad de archivos en $2 con permisos de ejecucion $cont"
	exit 0
fi
exit 1
