#!/bin/bash

contador=0 

while [ $contador -le 10 ]; do
	firefox=$(ps -e | grep -c firefox)
	if [ $firefox -ne 0 ]; then
		echo "Se encontraron $contador proceso/s firefox"
		contador=$(($contador + 1))
	fi
	if [ $contador -eq 10 ]; then
		echo "Se encontraron $contador procesos de firefox"
		echo "llego al contador 10"
		exit 0
	fi
	sleep 5
done
